export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GOT_EMPLOYEES = "GOT_EMPLOYEES";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const EMPLOYEE_UPDATED = "EMPLOYEE_UPDATED";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EMPLOYEE_DELETED = "EMPLOYEE_DELETED";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EMPLOYEE_ADDED = "EMPLOYEE_ADDED";
